### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by rra88** [conda-forge/pillow-feedstock#141]
### Comment:

Hi,
Using 
**Python 3.9.16 | packaged by conda-forge | (feeb267e, Jan 18 2023, 16:20:57)
[PyPy 7.3.11 with MSC v.1929 64 bit (AMD64)] on win32**
and running 
**from matplotlib import pyplot as plt**
results in the error message
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path-to-my-environment\lib\site-packages\matplotlib\__init__.py", line 131, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "path-to-my-environment\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "path-to-my-environment\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
  File "<frozen importlib._bootstrap>", line 1058, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "path-to-my-environment\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '\_imaging' from 'PIL' (path-to-my-environment\lib\site-packages\PIL\__init__.py)**
My matplotlib version is 3.7.1 and pillow/PIL version is 9.4.0.

Does anyone know what might be the cause of this? According to [https://pillow.readthedocs.io/en/stable/installation.html#old-versions](url) Pillow >= 9.3 should work with Python 3.9, [https://matplotlib.org/stable/devel/min_dep_policy.html](url) matplotlib 3.7 should work with Python >= 3.8, and [https://matplotlib.org/stable/devel/dependencies.html](url) matplotlib should work with Pillow >= 6.2.

**Comment by ocefpaf** [comment]
@rra88 can you please fill the debugging info required in issue? Without that we cannot help you much. You can see it when opening the issue, all that bolierplate stuff that you probably just deleted when typing your message above.
